name: Estúdio Foco
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#0d1422'
    - '#59372d'
    - '#b76d4c'
    - '#f8a562'
  brandStrength: 0.5
  lightness: 0.4893893734551966
  saturation: 0.6568027155008167
  rhythmicContrast: 0.8303631360176951
purpose: []
