name: Estúdio Foco
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#0c0c0c'
    - '#777777'
    - '#d1d1d1'
    - '#9a9a9a'
  brandStrength: 0.7826006177347153
  lightness: 0.4893893734551966
  saturation: 0.6568027155008167
  rhythmicContrast: 0.8303631360176951
purpose: []
