name: Estúdio Foco
favicon: null
layout_spectrum: 0.6883224884513766
typography_spectrum: 0.6155976529698819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7826006177347153
  lightness: 0.4893893734551966
  saturation: 0.6568027155008167
  rhythmicContrast: 0.8303631360176951
purpose: []
